version: "3.5"

services:
  webserver:
    image: vjcspy/ebs-docker-php-nginx:7.3
    container_name: "${STACK_NAME}-web"
    domainname: "${STACK_NAME}-web"
    hostname: "${STACK_NAME}-web"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ebs-docker-network
    volumes:
      - /home/vjcspy/work/ggg/bom:/app/yt
      - /home/vjcspy/work/vinagiay/src/web:/app/vng
      - /home/vjcspy/work/vinagiay/src/vng_current:/app/vng_current
      - ./config/nginx/vhost.conf:/opt/docker/etc/nginx/vhost.conf
    env_file: .env
    environment:
      PHP_IDE_CONFIG: "serverName=mgt" #debug cli
      XDEBUG_REMOTE_AUTOSTART: 1
      XDEBUG_REMOTE_HOST: "host.docker.internal" #linux
  #      XDEBUG_REMOTE_HOST: "docker.for.mac.localhost" #mac
  mysql:
    image: mysql:5.7
    container_name: "${STACK_NAME}-db"
    domainname: "${STACK_NAME}-db"
    hostname: "${STACK_NAME}-db"
    ports:
      - "3306:3306"
    networks:
      - ebs-docker-network
    volumes:
      - ./docker_data/mysql:/var/lib/mysql
      - ./docker_data/logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file: .env
  #  rabbit:
  #    networks:
  #      - ebs-docker-network
  #    hostname: "${STACK_NAME}-rb"
  #    container_name: "${STACK_NAME}-rb"
  #    domainname: "${STACK_NAME}-rb"
  #    image: "rabbitmq:3-management"
  #    ports:
  #      - "15672:15672"
  #      - "5672:5672"
  #    environment:
  #      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
  #      RABBITMQ_DEFAULT_USER: "rabbitmq"
  #      RABBITMQ_DEFAULT_PASS: "rabbitmq"
  #      RABBITMQ_DEFAULT_VHOST: "/"
#    redis:
#        container_name: "${STACK_NAME}-rds"
#        domainname: "${STACK_NAME}-rds"
#        hostname: "${STACK_NAME}-rds"
#        image: redis:latest
#        # command: redis-server --appendonly yes --requirepass root
#        command: ["redis-server", "--appendonly", "yes"]
#        ports:
#            - "6379:6379"
#        networks:
#            - ebs-docker-network
#        env_file: .env
networks:
  ebs-docker-network:


